theme = "kanabetter"

[editor]
line-number = "relative"
auto-save = true
bufferline = "multiple"
cursorline = true
idle-timeout = 100
# completion-trigger-len = 1

[editor.statusline]
right = ["spinner", "file-encoding", "position", "position-percentage"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.indent-guides]
render = true
character = "▏"

[keys.normal]
D = ["ensure_selections_forward", "extend_to_line_end", "delete_selection"]
C-s = ":w"
0 = "goto_line_start"
"$" = "goto_line_end"

[keys.insert]
C-s = ":w"
C-space = "completion"
A-n = "select_next_sibling"
A-p = "select_prev_sibling"
